// code written by Alexis Mae Asuncion

import { supabase } from "../../config/supabaseConfig";

// Represents one row from the StressLog table in the database
export type StressLogRow = {
    id: number; // Unique ID for this log (auto-generated by DB)
    date: string; // Date in "YYYY-MM-DD" format
    time: string; // Time in "HH:MM:SS" format
    stressLevel: number; // Stress level (1–10)
    meditated: boolean;   // Whether the user meditated
    mood: number;         // Mood stored as a number (1–5)
    notes: string | null; // Optional notes (null if empty)
    userID: string;       // ID of the user (UUID)
};

// Converts mood labels used in the UI into numbers stored in the database
const moodToInt: Record<
    "Very Low" | "Low" | "Neutral" | "Good" | "Excellent",
    number
> = {
  "Very Low": 1,
  "Low": 2,
  "Neutral": 3,
  "Good": 4,
  "Excellent": 5,
};

// Pads a number with a leading zero if needed
// Example: 3 → "03", 12 → "12"
function pad2(n: number) {
  return String(n).padStart(2, "0");
}

// Converts a JavaScript Date object into Postgres friendly date and time strings
function toPgDateTimeParts(d: Date) {
  // Build "YYYY-MM-DD"
  const date = `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;

  // Build "HH:MM:SS"
  const time = `${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;

  return { date, time };
}

// Inserts a new stress log entry into the database
export async function insertStressLog(
    userId: string, // The logged-in user's ID
    entry: {
    moodLabel: "Very Low" | "Low" | "Neutral" | "Good" | "Excellent";
    stressLevel: number;   // Must be between 1 and 10
    notes?: string;        // Optional notes
    meditated?: boolean;   // Optional, defaults to false
    when?: Date;           // Optional date/time, defaults to now
  }
): Promise<{
  success: boolean;
  data?: StressLogRow;
  error?: string;
}> {
  try {
    // Make sure we have a user ID
    if (!userId) {
      return { success: false, error: "Missing user id." };
    }

    // Ensure stress level is within allowed range
    if (entry.stressLevel < 1 || entry.stressLevel > 10) {
      return {
        success: false,
        error: "Stress level must be between 1 and 10.",
      };
    }

    // Convert mood label "Good" into a number 4
    const moodInt = moodToInt[entry.moodLabel];

    // Use the provided date/time or fall back to the current moment
    const when = entry.when ?? new Date();

     // Convert Date into Postgres friendly strings
    const { date, time } = toPgDateTimeParts(when);

    // Insert the row into the StressLog table
    const { data, error } = await supabase
      .from("StressLog")
      .insert({
        userID: userId,
        date,
        time,
        stressLevel: entry.stressLevel,
        meditated: entry.meditated ?? false, // Default to false
        mood: moodInt,
        // Trim notes; if empty, store null instead
        notes: entry.notes?.trim() ? entry.notes.trim() : null,
      })

      .select("*") // Ask Supabase to return the inserted row
      .single();   // Expect exactly one row back

      // If Supabase returned an error, report it
    if (error) {
      return { success: false, error: error.message };
    }

    // Success! Return the inserted row
    return { success: true, data: data as StressLogRow };

  } catch (err) {
    // Catch any unexpected errors
    return { success: false, error: String(err) };
  }
}